openapi: 3.0.0
info:
  title: Person Service API
  version: 1.0.0
  description: API documentation for managing personnel data
  contact:
    name: Zakhar Zakharchuk

tags:
  - name: PersonApi
    description: Operations related to personnel management

paths:
  /person:
    post:
      tags:
        - Person
      summary: Save a new person record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonRequest'
      responses:
        '200':
          description: Person record created
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

    put:
      tags:
        - Person
      summary: Update person details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '204':
          description: Person updated
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '404':
          description: Person not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

  /person/{id}:
    get:
      tags:
        - Person
      summary: Find person by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Person found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Invalid ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '404':
          description: Person not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

    delete:
      tags:
        - Person
      summary: Delete person record
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Person deleted
        '400':
          description: Invalid ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '404':
          description: Person not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        location:
          type: string
        dateOfBirth:
          type: string
          format: date-time
        startOfServiceDate:
          type: string
          format: date-time
        rank:
          type: string
        department:
          type: string
        currentPosition:
          type: string
        commanderId:
          type: string
        lastUpdated:
          type: string
          format: date-time

    CreatePersonRequest:
      type: object
      required:
        - name
        - surname
        - email
        - password
        - role
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        location:
          type: string
        dateOfBirth:
          type: string
          format: date-time
        startOfServiceDate:
          type: string
          format: date-time
        rank:
          type: string
        department:
          type: string
        currentPosition:
          type: string
        commanderId:
          type: string
        password:
          type: string
          description: Hashed or raw password to be forwarded to auth-service
        role:
          type: string
          enum: [USER, ADMIN, HR, MANAGER]

    BaseErrorResponse:
      title: BaseErrorResponse
      required:
        - type
        - title
        - instance
      type: object
      properties:
        type:
          type: string
          description: Type of the error
        title:
          type: string
          description: Title of the error
        instance:
          type: string
          description: URI or request path where the error occurred
        details:
          type: string
          description: Detailed error message
