spring:
  application:
    name: qualification-svc
  data:
    mongodb:
      uri: mongodb://localhost:27017/qualificationdb
      database: qualificationdb
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      security:
        protocol: PLAINTEXT
      sasl:
        mechanism: PLAIN

messaging:
  events:
    qualification:
      send-topic: qualification-updates-json
    person:
      receive-topic: person-updates-json
      consumer-group-id: person-updates-qualification
      dlq-topic: person-updates-dlq
      event-types: "PersonDeleted"
    retry-interval: 10000

server:
  port: 8082


