openapi: 3.0.0
info:
  title: HR Selection Service API
  version: 1.0.0

paths:
  /selection:
    post:
      summary: Add user to HR selection list
      tags:
        - HR Selection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddToSelectionRequest'
      responses:
        '201':
          description: User successfully added to selection list
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

    delete:
      summary: Remove user from HR selection list
      tags:
        - HR Selection
      parameters:
        - name: selectionId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User successfully removed from selection list
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '404':
          description: Entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

    get:
      summary: Get all selected users for the current HR
      tags:
        - HR Selection
      responses:
        '200':
          description: List of selected users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HRSelectionEntry'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

  /selection/status:
    put:
      summary: Update the HR status of a selected candidate
      tags:
        - HR Selection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSelectionStatusRequest'
      responses:
        '200':
          description: Status updated successfully
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '404':
          description: Selection not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseErrorResponse'

components:
  schemas:
    AddToSelectionRequest:
      type: object
      required:
        - candidateId
        - note
      properties:
        candidateId:
          type: string
        note:
          type: string
          description: HR's note about the person

    UpdateSelectionStatusRequest:
      type: object
      required:
        - selectionId
        - status
      properties:
        selectionId:
          type: string
        status:
          type: string
          enum: [PENDING, REVIEWED, SHORTLISTED, REJECTED]

    HRSelectionEntry:
      type: object
      properties:
        id:
          type: string
        hrId:
          type: string
        candidateId:
          type: string
        note:
          type: string
        status:
          type: string
          enum: [PENDING, REVIEWED, SHORTLISTED, REJECTED]

    BaseErrorResponse:
      title: BaseErrorResponse
      required:
        - type
        - title
        - instance
      type: object
      properties:
        type:
          type: string
          description: Type of the error
        title:
          type: string
          description: Title of the error
        instance:
          type: string
          description: URI or request path where the error occurred
        details:
          type: string
          description: Detailed error message
